rental_app/urls.py
from django.conf.urls import url
from rental_app import views
from django.contrib import admin
from django.urls import path

app_name= 'rental_app'
urlpatterns = [

    path('book/', views.book_list, name='book_list'),
    path('book_update/<int:id>', views.book_update, name='book_update'),
    path('book_add/', views.book_add, name='book_add'),
    path('book_delete/<int:id>', views.book_delete, name='book_delete'),


    path('customer/', views.customer_add, name='customer'),
    path('customer_update/<int:id>', views.customer_update, name='customer_update'),
    path('customer_delete/<int:id>', views.customer_delete, name='customer_delete'),
    path('customer_display_info/<int:id>', views.customer_display_info, name='customer_display_info'),

        ]

rental_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from rental_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('index/',views.index, name='index'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/',views.user_logout, name='logout'),
    path('reset_password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password/done/', views.PasswordResetDoneView.as_view(), name='reset_password_done'),
    path('reset_confirmation/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(),
         name='reset_password_confirmation'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='reset_password_complete'),
    path('password_change/', views.ChangePasswordResetDoneView.as_view(), name='password_change'),
    path('password_changedone', views.ChangePasswordResetDoneSuccessView.as_view(), name='password_changedone'),
    path('rental/', include('rental_app.urls')),

]

rental_app/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.core.exceptions import ValidationError

def __str__(self):
        return str(self.type_name)

class BedType(models.Model):
    type_name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.type_name

class Customer (models.Model):
        first_name = models.CharField(max_length=100, blank=True, null=True)
        last_name = models.CharField(max_length=100, blank=True, null=True)
        dob = models.DateField()
        gender = models.CharField(max_length=8)
        email = models.CharField(max_length=100,unique=True)
        address1 = models.CharField(max_length=250)
        address2 = models.CharField(max_length=250)
        mobile = models.CharField(max_length=14, unique=True)


        def __str__(self):
            full_name = self.first_name+' '+self.last_name
            return full_name

class Book (models.Model):
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    check_in = models.DateField()
    check_out = models.DateField()
    room_number = models.PositiveIntegerField()
    BedType = models.ForeignKey(BedType, on_delete=models.CASCADE)
    special_req = models.CharField(max_length=250)

    def __str__(self):
        return self.customer_id.first_name

    def clean(self):
        super(Book, self).clean()
        req_Book = Book.objects.filter(room_number=self.room_number)

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

rental_app/forms.py
from django import forms
from django.forms import ValidationError
from django.core import validators
from django.contrib.auth.models import User
from rental_app.models import UserInfo, Book, Customer


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

#--------------------------------------------------------------------------------
class DateInput(forms.DateInput):
    input_type = 'date'


class FormBook(forms.ModelForm):

    class Meta():
        widgets = {'check_in' : DateInput(), 'check_out' : DateInput}
        model = Book
        fields = ('customer_id','check_in','check_out','BedType', 'special_req', 'room_number')

class FormCustomer(forms.ModelForm):

    class Meta():
        widgets = {'dob': DateInput()}
        model = Customer
        fields = ('first_name', 'last_name', 'dob', 'gender', 'email', 'address1', 'address2', 'mobile')

rental_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import forms
from rental_app.models import BedType, Book, Customer
from rental_app.forms import UserForm, FormBook, FormCustomer
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login, logout  # for later
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.forms import formset_factory
from django.forms import modelformset_factory
from django.contrib.auth import views as auth_views, forms as auth_forms
from django.urls import reverse_lazy


def user_logout(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (user_login, request.path))

    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print('someone tried to login and failed :(')
            print('username: {} password: {}'.format(username, password))
            return HttpResponse('invalid login details supplied')

    else:
        return render(request, 'login.html', {})


def index(request):
    return render(request, 'index.html')

@login_required(login_url='user_login')
def book_list(request):
        book_list = Book.objects.order_by('check_in')
        book = {'book': book_list}
        return render(request, 'book_list.html', context=book)

@login_required(login_url='user_login')
def book_update(request, id):
    instance = get_object_or_404(Book, id=id)
    book_form = FormBook(instance=instance)
    if request.method == "POST":
        book_form = FormBook(data=request.POST, instance=instance)
        if book_form.is_valid():
            book = book_form.save()
            book.save()
            messages.add_message(request, messages.SUCCESS,'Booking was updated successfully')
            return redirect('rental_app:book_list')
        else:
            print(book_form.errors)
    else:  # http request
        book_form = FormBook(instance=instance)
    return render(request, 'book_update.html', {'book_form': book_form, 'book': instance})

@login_required(login_url='user_login')
def book_add(request):
    if request.method == "POST":
        book_form = FormBook(data=request.POST)
        if book_form.is_valid():
            book_form.save()
            messages.add_message(request, messages.SUCCESS,'Booking was added successfully')
            return redirect('rental_app:book_list')
        else:
            print(book_form.errors)
    else:  # http request
        book_form = FormBook()
    return render(request, 'book_update.html', {'book_form': book_form,})

@login_required(login_url='user_login')
def book_delete(request, id):
    instance = get_object_or_404(Book, id=id)
    instance.delete()
    messages.add_message(request, messages.SUCCESS,'Booking was deleted successfully')
    return HttpResponseRedirect(reverse('rental_app:book_list'))


# ================================================================================


@login_required(login_url='user_login')
def customer_update(request, id):
    instance = get_object_or_404(Customer, id=id)
    customer_form = FormCustomer(instance=instance)
    if request.method == "POST":
        customer_form = FormCustomer(data=request.POST, instance=instance)
        if customer_form.is_valid():
            customer_form.save()
            messages.add_message(request, messages.SUCCESS,'Customer was updated successfully')
            return redirect('rental_app:customer')
        else:
            print(customer_form.errors)
    else:  # http request
        customer_form = FormCustomer(instance=instance)
    return render(request, 'customer_update.html', {'customer_form': customer_form, 'customer': instance})

@login_required(login_url='user_login')
def customer_delete(request, id):
    instance = get_object_or_404(Customer, id=id)
    instance.delete()
    messages.add_message(request, messages.SUCCESS,'Customer was deleted successfully')
    return HttpResponseRedirect(reverse('rental_app:customer'))

@login_required(login_url='user_login')
def customer_add(request):
    CustomerFormSet = modelformset_factory(Customer,form=FormCustomer,fields=('__all__'), extra=3)
    form = CustomerFormSet(queryset=Customer.objects.none())
    if request.method == 'POST':
        form = CustomerFormSet(request.POST)
        if form.is_valid():
            form.save()
            form = CustomerFormSet(queryset=Customer.objects.none())
    # display all customer
    queryset = Customer.objects.all().order_by('first_name')
    context = {'customer':queryset,'form': form}
    return render(request, 'customer_list.html', context)

@login_required(login_url='user_login')
def customer_display_info(request, id):
    instance=get_object_or_404(Customer, id=id)

    return render(request, 'customer_display_info.html', {'instance': instance})

class ChangePasswordResetDoneView(auth_views.PasswordChangeView):
    form_class = auth_forms.PasswordChangeForm
    template_name = 'password_change.html'
    success_url = reverse_lazy('password_changedone')

class ChangePasswordResetDoneSuccessView(auth_views.PasswordChangeView):
    form_class = auth_forms.PasswordChangeForm
    template_name = 'password_changedone.html'

class PasswordResetView(auth_views.PasswordResetView):
    form_class = auth_forms.PasswordResetForm
    template_name = 'reset_password.html'
    email_template_name = 'reset_password_email.html'
    success_url = reverse_lazy('reset_password_done')

class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    form_class = auth_forms.PasswordResetForm
    template_name = 'reset_password_done.html'
    #success_url = reverse_lazy('reset_password_done')

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    form_class = auth_forms.SetPasswordForm
    template_name = 'reset_password_confirm.html'
    success_url = reverse_lazy('reset_password_complete')

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    form_class = auth_forms.PasswordResetForm
    template_name = 'reset_password_complete.html'
    #success_url = reverse_lazy('login.html')

rental_app/templates/book_list.html
<!DOCTYPE html>
{% extends "master.html" %}
  {% block body_block %}

    <h2>Bookings List</h2>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
<br>
    <div class="records">

      {% csrf_token %}
      {% if book %}

        <table class="table">
        <thead>
          <th scope="col">Check-in</th>
          <th scope="col"> &nbsp Check-out</th>
          <th scope="col"> &nbsp Customer </th>
          <th scope="col"> &nbsp Update </th>
          <th scope="col"> &nbsp Delete</th>
        </thead>
        {% for i in book %}
          <tr>
              <td scope="row">{{i.check_in}}</td>
              <td scope="row"> &nbsp {{i.check_out}}</td>
              <td scope="row">&nbsp &nbsp<a href="{% url 'rental_app:customer_display_info' i.customer_id.id %}">{{i.customer_id.first_name}}</a></td>
              <td scope="row">&nbsp &nbsp<a href="{% url 'rental_app:book_update' i.id %}" class="btn btn-info">update</a></td>
              <td scope="row">&nbsp &nbsp<a href="#" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal{{i.id}}">delete</a></td>

              <div class="modal fade in" id="delete-modal{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="delete-modal" aria-hidden="true">
                 <div class="modal-dialog">
                   <div class="modal-content">
                     <div class="modal-body">
                       <p>You are about to delete a record {{i.customer_id.first_name}}. Do you want to continue?</p>
                       <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                       <a href="{% url 'rental_app:book_delete' i.id %}" class="btn btn-danger" type="button">Yes</a>
                     </div>
                   </div>
                 </div>
               </div>
          </tr>
          {% endfor %}
      </table>
      {% else %}
          <p>no records found</p>
        {% endif %}
      </br></br></br>
     <a href="{% url 'rental_app:book_add' %}"><input type="submit" class="btn btn-primary" value="Add a Booking"></a>
      </div>
      {% endblock %}

rental_app/templates/book_update.html
<!DOCTYPE html>
{% extends "master.html" %}
  {% block body_block %}


  <body>
      <h1>Fill out the form</h1>
        <div class='container'>
          <form method="POST">
            {{book_form.as_p}}
            {% csrf_token %}
            
            <input type="submit" class="btn btn-primary" value="Submit">
          </form>
        </div>
    </body>
      {% endblock %}

rental_app/templates/customer_display_info.html
<!DOCTYPE html>
{% extends "master.html" %}
  {% block body_block %}

    <h2>Customer Info</h2>

    <div class="info">

      {% csrf_token %}
      {% if instance %}
      <table class="table">
        <thead>
          <th scope="col">First Name</th>
          <th scope="col"> &nbsp Last Name</th>
          <th scope="col"> &nbsp Date of Birth </th>
          <th scope="col"> &nbsp Gender </th>
          <th scope="col"> &nbsp E-mail </th>
          <th scope="col"> &nbsp address 1 </th>
          <th scope="col"> &nbsp address 2 </th>
          <th scope="col"> &nbsp Cell Phone No.</th>

        </thead>

          <tr>
              <td scope="row">{{instance.first_name}}</td>
              <td scope="row">{{instance.last_name}}</td>
              <td scope="row">{{instance.dob}}</td>
              <td scope="row">{{instance.gender}}</td>
              <td scope="row">{{instance.email}}</td>
              <td scope="row">{{instance.address1}}</td>
              <td scope="row">{{instance.address2}}</td>
              <td scope="row">{{instance.mobile}}</td>


          </tr>
        {% endif %}
</table>


      {% endblock %}

rental_app/templates/customer_list.html
<!DOCTYPE html>
{% extends "master.html" %}
{% block body_block %}

<h2>Customer</h2>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}



<form action="" method="post">
  <div class="scrollmenu">
    <table class="table table-bordered table-striped table-sm">
      {% csrf_token %}
      {{ form.management_form }}
      {% for form in form %}
      {{ form.id }}
      {% if forloop.first %}
      <thead>
        <tr>
          {% for field in form.visible_fields %}
          <th>{{ field.label|capfirst }}</th>
          {% endfor %}
        </tr>
      </thead>
      {% endif %}
      <tr>
        {% for field in form.visible_fields %}
        <td>
          {% if forloop.first %}
          {% for hidden in form.hidden_fields %}
          {{ hidden }}
          {% endfor %}
          {% endif %}
          {{ field.errors.as_ul }}
          {{ field }}
        </td>
        {% endfor %}
      </tr>
      {% endfor %}
      <br>
    </table>
  </div>
  <br>
  <button type="submit" name="button" class="btn btn-primary">Submit</button>
</form>


<br><br>

<div class="records">

  {% csrf_token %}
  {% if customer %}
  <table class="table">
    <thead>
      <th scope="col">First Name</th>
      <th scope="col"> &nbsp Last Name</th>
      <th scope="col"> &nbsp Cell Phone No.</th>
      <th scope="col"> &nbsp Update </th>
      <th scope="col"> &nbsp Delete</th>
    </thead>
    {% for i in customer %}
    <tbody>
      <tr>
        <td scope="row"><a href="{% url 'rental_app:customer_display_info' i.id %}">{{i.first_name}}</a></td>
        <td scope="row">{{i.last_name}}</td>
        <td scope="row">&nbsp &nbsp{{i.mobile}}</td>
        <td scope="row">&nbsp &nbsp<a href="{% url 'rental_app:customer_update' i.id %}" class="btn btn-info">update</a></td>
        <td scope="row">&nbsp &nbsp<a href="#" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal{{i.id}}">delete</a></td>

        <div class="modal fade in" id="delete-modal{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="delete-modal" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-body">
                <p>You are about to delete a record. Do you want to continue?</p>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <a href="{% url 'rental_app:customer_delete' i.id %}" class="btn btn-danger" type="button">Yes</a>
              </div>
            </div>
          </div>
        </div>
      </tr>

    </tbody>
    {% endfor %}
  </table>
  {% else %}
  <p>no records found</p>
  {% endif %}
  </br></br></br>



</div>



{% endblock %}

rental_app/templates/customer_update.html
<!DOCTYPE html>
{% extends "master.html" %}
  {% block body_block %}


  <body>
      <h1>Fill out the form</h1>
        <div class='container'>
          <form method="POST">
            {{customer_form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
          </form>
        </div>
    </body>
      {% endblock %}

rental_app/templates/index.html
<!DOCTYPE html>
{% extends "master.html" %}
{% load static %}
  {% block body_block %}
<head><link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

  <div class="jumbotron">

  {% if request.user.is_authenticated %}
   <h1>Hi Welcome {{ request.user.username|title}}</h1> <br>
      <h2>Thank you for logging in and working for us! Please proceed with your job duties!</h2>
{% else %}
<h1>Hi Welcome</h1><br>
      <h2>Room Rental App is a room booking management system. This is used by us (a motel) to keep track of our rooms, bookings and customers. If you want to book a room with us, please call (123) 456 7890 and a receptionist will be happy to help you through your booking process! Thank you!</h2> <br>
      <h3>If you are a receptionist who works with us, please login and proceed with your job duties.</h3> <br>
      <h4>If you are a new hire receptionist, please contact your manager/supervisor for your login details.</h4>
{% endif %}

</div>
      {% endblock %}

rental_app/templates/login.html
<!DOCTYPE html>
{% extends "master.html" %}
  {% block body_block %}
<div class="jumbotron">
<h1>Please Login</h1>
<form action="{% url 'user_login' %}" method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Enter Username"="">
  <label for="password">Password</label>
  <input type="password" name="password" >

  <input type="submit" name="" value="Login">
        <br>
        <br>
        <a href="{% url 'reset_password' %}">Forgot Password?</a>
</form>
</div>

  {% endblock %}

rental_app/templates/password_change.html
{% extends "master.html" %}

{% block title %}Reset Password{% endblock %}

{% block body_block %}
<p>Change Password</p>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save changes</button>
</form>
{% endblock %}

rental_app/templates/password_changedone.html
{% extends "master.html" %}

{% block title %}Password reset successful{% endblock %}

{% block body_block %}
<p>Successfully changed password !</p>

{% endblock %}

rental_app/templates/reset_password.html
{% extends "master.html" %}

{% block title %}Reset Password{% endblock %}

{% block body_block %}
<p>Please specify your email address to receive instructions for resetting it.</p>

<form action="" method="post">
    <div style="display:none">
        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    </div>
     {{ form.email.errors }}
    <p><label for="id_email">E-mail address:</label> {{ form.email }} <input type="submit" value="Reset password" /></p>
</form>
{% endblock %}

rental_app/templates/reset_password_complete.html
{% extends "master.html" %}

{% block title %}Password reset complete{% endblock %}

{% block body_block %}
<p>You have successfully reset your password! Click on "Log In" below to login with your new credentials.</p>
<p><a href="{% url 'user_login' %}">Log in</a></p>
{% endblock %}

rental_app/templates/reset_password_confirm.html
{% extends "master.html" %}
{% block title %}Setting New password{% endblock %}

{% block body_block %}
    {% if validlink %}
        <p>Please enter your new password twice.<br />
           So we can verify you typed it in correctly.</p>
        <form action="" method="post">
            <div style="display:none">
                <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
            </div>
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1">New password:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2">Confirm password:</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Change my password" /></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Password reset unsuccessful</h1>
        <p>The password reset link was invalid, possibly because it has already been used. Please try resetting it again.</p>
    {% endif %}
{% endblock %}

rental_app/templates/reset_password_done.html
{% extends "master.html" %}

{% block title %}Password reset successful{% endblock %}

{% block body_block %}
<p>If you have an existing account with us, you will be receiving an e-mail with instructions for resetting your password.</p>
{% endblock %}

rental_app/templates/reset_password_email.html
{% autoescape off %}
You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'reset_password_confirmation' uidb64=uid token=token %}
{% endblock %}

Your username, in case you've forgotten: {{ user.username }}

Thanks for using our site!

The {{ site_name }} team.

{% endautoescape %}